# Timing Constraints (SDC)
# Generated by sram-forge
# Chip: gf180mcu_ic_1x1_sram_u8b24k

# Clock definition
# Frequency: 25.0 MHz
# Period: 40.0 ns
create_clock -name clk -period 40.0 [get_ports clk_pad]

# Clock uncertainty (jitter + skew)
set_clock_uncertainty 0.5 [get_clocks clk]

# Clock transition time
set_clock_transition 0.5 [get_clocks clk]

# Input delays (relative to clock)
# Assume 25% of clock period for setup
set input_delay [expr 40.0 * 0.25]
set_input_delay -clock clk -max $input_delay [get_ports {ce_n_pad we_n_pad}]
set_input_delay -clock clk -max $input_delay [get_ports {addr_pad_*}]
set_input_delay -clock clk -max $input_delay [get_ports {data_pad_*}]

# Reset is asynchronous
set_input_delay -clock clk -max $input_delay [get_ports rst_n_pad]

# Output delays (relative to clock)
# Assume 25% of clock period for hold
set output_delay [expr 40.0 * 0.25]
set_output_delay -clock clk -max $output_delay [get_ports {data_pad_*}]

# SRAM timing constraints
# Read latency: 1 cycle
# Write latency: 1 cycle
# SRAM minimum cycle time: 6.077 ns
# SRAM clock-to-Q: 5.008 ns

# False paths
# Reset is asynchronous
set_false_path -from [get_ports rst_n_pad]

# Max transition and capacitance
set_max_transition 1.0 [current_design]
set_max_fanout 10 [current_design]

# Operating conditions
set_operating_conditions -max tt_025C_5v00 -max_library gf180mcu_fd_sc_mcu7t5v0__tt_025C_5v00

# Report settings
report_checks -path_delay max -through [get_pins -of_objects [get_cells -hierarchical -filter "ref_name == gf180mcu_fd_ip_sram__sram512x8m8wm1"] -filter "name =~ *CLK*"]