# AUTOGENERATED by scripts/generate_exact_3side_configs.py -- DO NOT EDIT.
#
# Exact-pad PAD_CFG for slot_0p5x0p5_2side_exact.
#
# This replays LibreLane common/pad_cfg.tcl's cur_pos arithmetic
# using slot_1x1's die dimension + full per-edge pad count, then
# issues, for every retained pad, the identical place_pad -location
# call the real slot_1x1 build issued for that 1x1 ordinal -- giving
# byte-identical pad coordinates.  (S/N: 1x1 die=3932 n=17; E/W:
# 1x1 die=5122 n=20.  Constants from the PDK IO config:
# PAD_EDGE_SPACING=26, PAD_FAKE_CORNER_SITE=355, PAD_FAKE_SITE=0.1.)

source $::env(SCRIPTS_DIR)/openroad/common/set_global_connections.tcl
set_global_connections

puts "\[INFO\] Generating EXACT-pad padring for 0p5x0p5_2side_exact…"

make_io_sites \
    -horizontal_site $::env(PAD_SITE_NAME) \
    -vertical_site $::env(PAD_SITE_NAME) \
    -corner_site $::env(PAD_CORNER_SITE_NAME) \
    -offset $::env(PAD_EDGE_SPACING)

set block [ord::get_db_block]

# ---- slot_1x1 cur_pos replay helper ---------------------------------
# Reproduces pad_cfg.tcl lines 73-131 for a slot_1x1 edge and returns
# the list of cur_pos values (one per 1x1 ordinal, all pads 75um).
proc lx_1x1_curpos {die_dim n_pads is_horizontal} {
    set es $::env(PAD_EDGE_SPACING)
    if {$is_horizontal} {
        set corner $::env(PAD_FAKE_CORNER_SITE_WIDTH)
    } else {
        set corner $::env(PAD_FAKE_CORNER_SITE_HEIGHT)
    }
    set site $::env(PAD_FAKE_SITE_WIDTH)
    set pad_w 75
    set side_width [expr {$die_dim - $es*2 - $corner*2}]
    set sum_w [expr {$pad_w * $n_pads}]
    set fill [expr {$side_width - $sum_w}]
    set sbp [expr {$fill / ($n_pads + 1)}]
    set sbp1 [expr {floor($sbp / $site) * $site}]
    set sspace [expr {($fill - $sbp1*($n_pads-1)) / 2.0}]
    set cur [expr {$sspace + $es + $corner}]
    set out {}
    for {set i 0} {$i < $n_pads} {incr i} {
        lappend out $cur
        set cur [expr {$cur + $sbp1 + $pad_w}]
    }
    return $out
}

proc lx_place {block row inst loc} {
    if { [set i [$block findInst $inst]] == "NULL" } {
        puts stderr "\[ERROR\] exact PAD_CFG: instance $inst not found"
        exit 1
    }
    place_pad -row $row -location $loc \
        -master [[$i getMaster] getName] $inst
}

# ---- IO_SOUTH (PAD_SOUTH) ----
set cp_S [lx_1x1_curpos 3932 17 1]
lx_place $block IO_SOUTH "clk_pad" [lindex $cp_S 0]  ;# 1x1 ordinal 0
lx_place $block IO_SOUTH "rst_n_pad" [lindex $cp_S 1]  ;# 1x1 ordinal 1
lx_place $block IO_SOUTH "bidir\[0\].pad" [lindex $cp_S 2]  ;# 1x1 ordinal 2
lx_place $block IO_SOUTH "bidir\[1\].pad" [lindex $cp_S 3]  ;# 1x1 ordinal 3
lx_place $block IO_SOUTH "bidir\[2\].pad" [lindex $cp_S 4]  ;# 1x1 ordinal 4
lx_place $block IO_SOUTH "bidir\[3\].pad" [lindex $cp_S 5]  ;# 1x1 ordinal 5
lx_place $block IO_SOUTH "analog\[0\].pad" 1464.5000  ;# relocated analog (NOT 1x1-preserved)

# PAD_EAST: bare cut edge -- no pads

# PAD_NORTH: bare cut edge -- no pads

# ---- IO_WEST (PAD_WEST) ----
set cp_W [lx_1x1_curpos 5122 20 0]
lx_place $block IO_WEST "inputs\[0\].pad" [lindex $cp_W 0]  ;# 1x1 ordinal 0
lx_place $block IO_WEST "inputs\[1\].pad" [lindex $cp_W 1]  ;# 1x1 ordinal 1
lx_place $block IO_WEST "dvss_pads\[0\].pad" [lindex $cp_W 2]  ;# 1x1 ordinal 2
lx_place $block IO_WEST "dvdd_pads\[0\].pad" [lindex $cp_W 3]  ;# 1x1 ordinal 3
lx_place $block IO_WEST "inputs\[2\].pad" [lindex $cp_W 4]  ;# 1x1 ordinal 4
lx_place $block IO_WEST "inputs\[3\].pad" [lindex $cp_W 5]  ;# 1x1 ordinal 5
lx_place $block IO_WEST "inputs\[4\].pad" [lindex $cp_W 6]  ;# 1x1 ordinal 6
lx_place $block IO_WEST "inputs\[5\].pad" [lindex $cp_W 7]  ;# 1x1 ordinal 7
lx_place $block IO_WEST "analog\[1\].pad" 2072.0000  ;# relocated analog (NOT 1x1-preserved)

puts "\[INFO\] Placing corner cells…"
place_corners $::env(PAD_CORNER)

puts "\[INFO\] Placing filler cells…"
place_io_fill -row IO_NORTH {*}$::env(PAD_FILLERS)
place_io_fill -row IO_SOUTH {*}$::env(PAD_FILLERS)
place_io_fill -row IO_WEST {*}$::env(PAD_FILLERS)
place_io_fill -row IO_EAST {*}$::env(PAD_FILLERS)

puts "\[INFO\] Connecting ring signals…"
connect_by_abutment

# Place io terminals (matches stock pad_cfg.tcl).
if { [info exists ::env(PAD_PLACE_IO_TERMINALS)] } {
    puts "\[INFO\] Placing I/O terminals…"
    foreach side {PAD_SOUTH PAD_EAST PAD_NORTH PAD_WEST} {
        if { ![info exists ::env($side)] } { continue }
        foreach inst_name $::env($side) {
            if { [set inst [$block findInst $inst_name]] == "NULL" } { continue }
            set master_name [[$inst getMaster] getName]
            foreach master_pin $::env(PAD_PLACE_IO_TERMINALS) {
                set parts [split $master_pin /]
                if {$master_name == [lindex $parts 0]} {
                    place_io_terminals $inst_name/[lindex $parts 1]
                    break
                }
            }
        }
    }
}

puts "\[INFO\] Removing I/O rows…"
remove_io_rows
