# AUTOGENERATED by scripts/generate_exact_3side_configs.py -- DO NOT EDIT.
#
# Exact-pad PAD_CFG for slot_0p5x1_3side_exact.
#
# This replays LibreLane common/pad_cfg.tcl's cur_pos arithmetic
# using slot_1x1's die dimension + full per-edge pad count, then
# issues, for every retained pad, the identical place_pad -location
# call the real slot_1x1 build issued for that 1x1 ordinal -- giving
# byte-identical pad coordinates.  (S/N: 1x1 die=3932 n=17; E/W:
# 1x1 die=5122 n=20.  Constants from the PDK IO config:
# PAD_EDGE_SPACING=26, PAD_FAKE_CORNER_SITE=355, PAD_FAKE_SITE=0.1.)

source $::env(SCRIPTS_DIR)/openroad/common/set_global_connections.tcl
set_global_connections

puts "\[INFO\] Generating EXACT-pad padring for 0p5x1_3side_exact…"

make_io_sites \
    -horizontal_site $::env(PAD_SITE_NAME) \
    -vertical_site $::env(PAD_SITE_NAME) \
    -corner_site $::env(PAD_CORNER_SITE_NAME) \
    -offset $::env(PAD_EDGE_SPACING)

set block [ord::get_db_block]

# ---- slot_1x1 cur_pos replay helper ---------------------------------
# Reproduces pad_cfg.tcl lines 73-131 for a slot_1x1 edge and returns
# the list of cur_pos values (one per 1x1 ordinal, all pads 75um).
proc lx_1x1_curpos {die_dim n_pads is_horizontal} {
    set es $::env(PAD_EDGE_SPACING)
    if {$is_horizontal} {
        set corner $::env(PAD_FAKE_CORNER_SITE_WIDTH)
    } else {
        set corner $::env(PAD_FAKE_CORNER_SITE_HEIGHT)
    }
    set site $::env(PAD_FAKE_SITE_WIDTH)
    set pad_w 75
    set side_width [expr {$die_dim - $es*2 - $corner*2}]
    set sum_w [expr {$pad_w * $n_pads}]
    set fill [expr {$side_width - $sum_w}]
    set sbp [expr {$fill / ($n_pads + 1)}]
    set sbp1 [expr {floor($sbp / $site) * $site}]
    set sspace [expr {($fill - $sbp1*($n_pads-1)) / 2.0}]
    set cur [expr {$sspace + $es + $corner}]
    set out {}
    for {set i 0} {$i < $n_pads} {incr i} {
        lappend out $cur
        set cur [expr {$cur + $sbp1 + $pad_w}]
    }
    return $out
}

# Place pad #idx of $::env($side) (the SAME resolved instance list
# stock pad_cfg.tcl iterates -- avoids any name re-escaping) at the
# given along-edge location.
proc lx_place {block side row idx loc} {
    set inst [lindex $::env($side) $idx]
    if { [set i [$block findInst $inst]] == "NULL" } {
        puts stderr "\[ERROR\] exact PAD_CFG: $side\[$idx\] ($inst) not found"
        exit 1
    }
    place_pad -row $row -location $loc \
        -master [[$i getMaster] getName] $inst
}

# ---- IO_SOUTH (PAD_SOUTH) ----
# PAD_SOUTH list order == placement order below (idx -> location).
set cp_S [lx_1x1_curpos 3932 17 1]
lx_place $block PAD_SOUTH IO_SOUTH 0 [lindex $cp_S 0]  ;# clk_pad @ 1x1 ordinal 0
lx_place $block PAD_SOUTH IO_SOUTH 1 [lindex $cp_S 1]  ;# rst_n_pad @ 1x1 ordinal 1
lx_place $block PAD_SOUTH IO_SOUTH 2 [lindex $cp_S 2]  ;# bidir[0].pad @ 1x1 ordinal 2
lx_place $block PAD_SOUTH IO_SOUTH 3 [lindex $cp_S 3]  ;# bidir[1].pad @ 1x1 ordinal 3
lx_place $block PAD_SOUTH IO_SOUTH 4 [lindex $cp_S 4]  ;# bidir[2].pad @ 1x1 ordinal 4
lx_place $block PAD_SOUTH IO_SOUTH 5 [lindex $cp_S 5]  ;# bidir[3].pad @ 1x1 ordinal 5

# PAD_EAST: bare cut edge -- no pads

# ---- IO_NORTH (PAD_NORTH) ----
# PAD_NORTH list order == placement order below (idx -> location).
set cp_N [lx_1x1_curpos 3932 17 1]
lx_place $block PAD_NORTH IO_NORTH 0 [lindex $cp_N 0]  ;# bidir[4].pad @ 1x1 ordinal 0
lx_place $block PAD_NORTH IO_NORTH 1 [lindex $cp_N 1]  ;# bidir[5].pad @ 1x1 ordinal 1
lx_place $block PAD_NORTH IO_NORTH 2 [lindex $cp_N 2]  ;# bidir[6].pad @ 1x1 ordinal 2
lx_place $block PAD_NORTH IO_NORTH 3 [lindex $cp_N 3]  ;# bidir[7].pad @ 1x1 ordinal 3
lx_place $block PAD_NORTH IO_NORTH 4 [lindex $cp_N 4]  ;# bidir[8].pad @ 1x1 ordinal 4
lx_place $block PAD_NORTH IO_NORTH 5 [lindex $cp_N 5]  ;# bidir[9].pad @ 1x1 ordinal 5

# ---- IO_WEST (PAD_WEST) ----
# PAD_WEST list order == placement order below (idx -> location).
set cp_W [lx_1x1_curpos 5122 20 0]
lx_place $block PAD_WEST IO_WEST 0 [lindex $cp_W 0]  ;# inputs[0].pad @ 1x1 ordinal 0
lx_place $block PAD_WEST IO_WEST 1 [lindex $cp_W 1]  ;# inputs[1].pad @ 1x1 ordinal 1
lx_place $block PAD_WEST IO_WEST 2 [lindex $cp_W 2]  ;# dvss_pads[0].pad @ 1x1 ordinal 2
lx_place $block PAD_WEST IO_WEST 3 [lindex $cp_W 3]  ;# dvdd_pads[0].pad @ 1x1 ordinal 3
lx_place $block PAD_WEST IO_WEST 4 [lindex $cp_W 4]  ;# inputs[2].pad @ 1x1 ordinal 4
lx_place $block PAD_WEST IO_WEST 5 [lindex $cp_W 5]  ;# inputs[3].pad @ 1x1 ordinal 5
lx_place $block PAD_WEST IO_WEST 6 [lindex $cp_W 6]  ;# inputs[4].pad @ 1x1 ordinal 6
lx_place $block PAD_WEST IO_WEST 7 [lindex $cp_W 7]  ;# inputs[5].pad @ 1x1 ordinal 7
lx_place $block PAD_WEST IO_WEST 8 [lindex $cp_W 8]  ;# dvss_pads[1].pad @ 1x1 ordinal 8
lx_place $block PAD_WEST IO_WEST 9 [lindex $cp_W 9]  ;# dvdd_pads[1].pad @ 1x1 ordinal 9
lx_place $block PAD_WEST IO_WEST 10 [lindex $cp_W 10]  ;# inputs[6].pad @ 1x1 ordinal 10
lx_place $block PAD_WEST IO_WEST 11 [lindex $cp_W 11]  ;# inputs[7].pad @ 1x1 ordinal 11
lx_place $block PAD_WEST IO_WEST 12 [lindex $cp_W 12]  ;# inputs[8].pad @ 1x1 ordinal 12
lx_place $block PAD_WEST IO_WEST 13 [lindex $cp_W 13]  ;# inputs[9].pad @ 1x1 ordinal 13
lx_place $block PAD_WEST IO_WEST 14 [lindex $cp_W 14]  ;# inputs[10].pad @ 1x1 ordinal 14
lx_place $block PAD_WEST IO_WEST 15 [lindex $cp_W 15]  ;# inputs[11].pad @ 1x1 ordinal 15
lx_place $block PAD_WEST IO_WEST 16 [lindex $cp_W 16]  ;# dvss_pads[2].pad @ 1x1 ordinal 16
lx_place $block PAD_WEST IO_WEST 17 [lindex $cp_W 17]  ;# dvdd_pads[2].pad @ 1x1 ordinal 17
lx_place $block PAD_WEST IO_WEST 18 [lindex $cp_W 18]  ;# dvss_pads[3].pad @ 1x1 ordinal 18
lx_place $block PAD_WEST IO_WEST 19 [lindex $cp_W 19]  ;# dvdd_pads[3].pad @ 1x1 ordinal 19

puts "\[INFO\] Placing corner cells…"
place_corners $::env(PAD_CORNER)

# Drop the bare-edge corner cell(s): no IO row abuts them, they would
# just be isolated structures on the bare cut edge.
set _bare_edges [list "east"]
set _xmid [expr {([lindex $::env(DIE_AREA) 0] + [lindex $::env(DIE_AREA) 2]) / 2.0}]
set _ymid [expr {([lindex $::env(DIE_AREA) 1] + [lindex $::env(DIE_AREA) 3]) / 2.0}]
set _units [$block getDefUnits]
# Identify bare-edge corner cells AND remember their bbox + side BEFORE
# destroying them -- the bbox is the freed silicon strip we will later
# fill with IO row fillers so the row visually extends to the die edge.
set _bare_corner_data [list]
foreach _inst [$block getInsts] {
    if { [[$_inst getMaster] getName] ne $::env(PAD_CORNER) } { continue }
    set _bb [$_inst getBBox]
    set _cx [expr {([$_bb xMin] + [$_bb xMax]) / 2.0 / $_units}]
    set _cy [expr {([$_bb yMin] + [$_bb yMax]) / 2.0 / $_units}]
    set _is_north [expr {$_cy > $_ymid}]
    set _is_east  [expr {$_cx > $_xmid}]
    set _drop 0
    foreach _edge $_bare_edges {
        switch -- $_edge {
            east  { if { $_is_east }      { set _drop 1 } }
            west  { if { ! $_is_east }    { set _drop 1 } }
            north { if { $_is_north }     { set _drop 1 } }
            south { if { ! $_is_north }   { set _drop 1 } }
        }
        if { $_drop } { break }
    }
    if { $_drop } {
        lappend _bare_corner_data [list [$_bb xMin] [$_bb yMin] \
            [$_bb xMax] [$_bb yMax] $_is_north $_inst]
    }
}
set _destroyed 0
foreach _data $_bare_corner_data {
    odb::dbInst_destroy [lindex $_data 5]
    incr _destroyed
}
puts "\[INFO\] Bare-edge corner cleanup (bare: $_bare_edges): destroyed $_destroyed corner cell(s)."

# Extend the adjacent IO row over the freed corner X strip by manually
# placing IO filler cells at the row's Y origin / orientation. This makes
# the N/S filler band run all the way to the die edge on a bare side
# rather than stopping ~355um short where the corner used to sit. The new
# fillers abut the row's last existing cell (same Y + orient + adjacent X)
# so they extend the power-abutment chain naturally for connect_by_abutment.
set _db [ord::get_db]
# Filler masters sorted by width (DB units) descending for greedy packing.
set _filler_choices [list]
foreach _fname $::env(PAD_FILLERS) {
    set _fm [$_db findMaster $_fname]
    if {$_fm == "NULL"} { continue }
    lappend _filler_choices [list [$_fm getWidth] $_fname $_fm]
}
set _filler_choices [lsort -decreasing -integer -index 0 $_filler_choices]
set _bare_fill_count 0
# Pre-iterate rows once; dbBlock has no findRow, just getRows.
set _rows_by_name [dict create]
foreach _r [$block getRows] {
    dict set _rows_by_name [$_r getName] $_r
}
foreach _data $_bare_corner_data {
    lassign $_data _cxlo _cylo _cxhi _cyhi _is_north _inst
    set _row_name [expr {$_is_north ? "IO_NORTH" : "IO_SOUTH"}]
    if {![dict exists $_rows_by_name $_row_name]} { continue }
    set _row [dict get $_rows_by_name $_row_name]
    # getBBox is the well-supported API across odb bindings; the row's
    # yMin is the Y origin of its sites (cells are placed at this Y).
    set _row_bb [$_row getBBox]
    set _row_y [$_row_bb yMin]
    set _row_orient [$_row getOrient]
    puts "\[INFO\]   ext row=$_row_name y=$_row_y orient=$_row_orient x=[$_row_bb xMin]-[$_row_bb xMax] corner_x=${_cxlo}-${_cxhi}"
    set _x $_cxlo
    while {$_x < $_cxhi} {
        set _rem [expr {$_cxhi - $_x}]
        set _placed 0
        foreach _fc $_filler_choices {
            lassign $_fc _fwidth _fname _fmaster
            if {$_fwidth <= $_rem} {
                incr _bare_fill_count
                set _iname "_bare_fill_$_bare_fill_count"
                set _new [odb::dbInst_create $block $_fmaster $_iname]
                $_new setOrient $_row_orient
                $_new setLocation $_x $_row_y
                $_new setPlacementStatus FIRM
                set _x [expr {$_x + $_fwidth}]
                set _placed 1
                break
            }
        }
        if {!$_placed} { break }
    }
}
puts "\[INFO\] Bare-edge corner fill: placed $_bare_fill_count extension filler(s)."

puts "\[INFO\] Placing filler cells…"
# Skip `place_io_fill` on bare-edge rows: no pads + no corners on
# that row means filler cells would be the only content, which is
# pure waste on a cut edge.
foreach _row {IO_NORTH IO_SOUTH IO_WEST IO_EAST} {
    set _edge_lc [string tolower [string range $_row 3 end]]
    if { [lsearch -exact $_bare_edges $_edge_lc] >= 0 } {
        puts "\[INFO\] Skipping place_io_fill on $_row (bare cut edge)"
        continue
    }
    place_io_fill -row $_row {*}$::env(PAD_FILLERS)
}

puts "\[INFO\] Connecting ring signals…"
connect_by_abutment

# Place io terminals (matches stock pad_cfg.tcl).
if { [info exists ::env(PAD_PLACE_IO_TERMINALS)] } {
    puts "\[INFO\] Placing I/O terminals…"
    foreach side {PAD_SOUTH PAD_EAST PAD_NORTH PAD_WEST} {
        if { ![info exists ::env($side)] } { continue }
        foreach inst_name $::env($side) {
            if { [set inst [$block findInst $inst_name]] == "NULL" } { continue }
            set master_name [[$inst getMaster] getName]
            foreach master_pin $::env(PAD_PLACE_IO_TERMINALS) {
                set parts [split $master_pin /]
                if {$master_name == [lindex $parts 0]} {
                    place_io_terminals $inst_name/[lindex $parts 1]
                    break
                }
            }
        }
    }
}

puts "\[INFO\] Removing I/O rows…"
remove_io_rows
