# AUTOGENERATED by scripts/generate_exact_3side_configs.py -- DO NOT EDIT.
#
# Exact-pad PAD_CFG for slot_1x0p5_3side_exact.
#
# This replays LibreLane common/pad_cfg.tcl's cur_pos arithmetic
# using slot_1x1's die dimension + full per-edge pad count, then
# issues, for every retained pad, the identical place_pad -location
# call the real slot_1x1 build issued for that 1x1 ordinal -- giving
# byte-identical pad coordinates.  (S/N: 1x1 die=3932 n=17; E/W:
# 1x1 die=5122 n=20.  Constants from the PDK IO config:
# PAD_EDGE_SPACING=26, PAD_FAKE_CORNER_SITE=355, PAD_FAKE_SITE=0.1.)

source $::env(SCRIPTS_DIR)/openroad/common/set_global_connections.tcl
set_global_connections

puts "\[INFO\] Generating EXACT-pad padring for 1x0p5_3side_exact…"

make_io_sites \
    -horizontal_site $::env(PAD_SITE_NAME) \
    -vertical_site $::env(PAD_SITE_NAME) \
    -corner_site $::env(PAD_CORNER_SITE_NAME) \
    -offset $::env(PAD_EDGE_SPACING)

set block [ord::get_db_block]

# ---- slot_1x1 cur_pos replay helper ---------------------------------
# Reproduces pad_cfg.tcl lines 73-131 for a slot_1x1 edge and returns
# the list of cur_pos values (one per 1x1 ordinal, all pads 75um).
proc lx_1x1_curpos {die_dim n_pads is_horizontal} {
    set es $::env(PAD_EDGE_SPACING)
    if {$is_horizontal} {
        set corner $::env(PAD_FAKE_CORNER_SITE_WIDTH)
    } else {
        set corner $::env(PAD_FAKE_CORNER_SITE_HEIGHT)
    }
    set site $::env(PAD_FAKE_SITE_WIDTH)
    set pad_w 75
    set side_width [expr {$die_dim - $es*2 - $corner*2}]
    set sum_w [expr {$pad_w * $n_pads}]
    set fill [expr {$side_width - $sum_w}]
    set sbp [expr {$fill / ($n_pads + 1)}]
    set sbp1 [expr {floor($sbp / $site) * $site}]
    set sspace [expr {($fill - $sbp1*($n_pads-1)) / 2.0}]
    set cur [expr {$sspace + $es + $corner}]
    set out {}
    for {set i 0} {$i < $n_pads} {incr i} {
        lappend out $cur
        set cur [expr {$cur + $sbp1 + $pad_w}]
    }
    return $out
}

# Place pad #idx of $::env($side) (the SAME resolved instance list
# stock pad_cfg.tcl iterates -- avoids any name re-escaping) at the
# given along-edge location.
proc lx_place {block side row idx loc} {
    set inst [lindex $::env($side) $idx]
    if { [set i [$block findInst $inst]] == "NULL" } {
        puts stderr "\[ERROR\] exact PAD_CFG: $side\[$idx\] ($inst) not found"
        exit 1
    }
    place_pad -row $row -location $loc \
        -master [[$i getMaster] getName] $inst
}

# ---- IO_SOUTH (PAD_SOUTH) ----
# PAD_SOUTH list order == placement order below (idx -> location).
set cp_S [lx_1x1_curpos 3932 17 1]
lx_place $block PAD_SOUTH IO_SOUTH 0 [lindex $cp_S 0]  ;# clk_pad @ 1x1 ordinal 0
lx_place $block PAD_SOUTH IO_SOUTH 1 [lindex $cp_S 1]  ;# rst_n_pad @ 1x1 ordinal 1
lx_place $block PAD_SOUTH IO_SOUTH 2 [lindex $cp_S 2]  ;# bidir[0].pad @ 1x1 ordinal 2
lx_place $block PAD_SOUTH IO_SOUTH 3 [lindex $cp_S 3]  ;# bidir[1].pad @ 1x1 ordinal 3
lx_place $block PAD_SOUTH IO_SOUTH 4 [lindex $cp_S 4]  ;# bidir[2].pad @ 1x1 ordinal 4
lx_place $block PAD_SOUTH IO_SOUTH 5 [lindex $cp_S 5]  ;# bidir[3].pad @ 1x1 ordinal 5
lx_place $block PAD_SOUTH IO_SOUTH 6 [lindex $cp_S 6]  ;# bidir[4].pad @ 1x1 ordinal 6
lx_place $block PAD_SOUTH IO_SOUTH 7 [lindex $cp_S 7]  ;# bidir[5].pad @ 1x1 ordinal 7
lx_place $block PAD_SOUTH IO_SOUTH 8 [lindex $cp_S 8]  ;# dvss_pads[0].pad @ 1x1 ordinal 8
lx_place $block PAD_SOUTH IO_SOUTH 9 [lindex $cp_S 9]  ;# bidir[6].pad @ 1x1 ordinal 9
lx_place $block PAD_SOUTH IO_SOUTH 10 [lindex $cp_S 10]  ;# bidir[7].pad @ 1x1 ordinal 10
lx_place $block PAD_SOUTH IO_SOUTH 11 [lindex $cp_S 11]  ;# bidir[8].pad @ 1x1 ordinal 11
lx_place $block PAD_SOUTH IO_SOUTH 12 [lindex $cp_S 12]  ;# bidir[9].pad @ 1x1 ordinal 12
lx_place $block PAD_SOUTH IO_SOUTH 13 [lindex $cp_S 13]  ;# bidir[10].pad @ 1x1 ordinal 13
lx_place $block PAD_SOUTH IO_SOUTH 14 [lindex $cp_S 14]  ;# bidir[11].pad @ 1x1 ordinal 14
lx_place $block PAD_SOUTH IO_SOUTH 15 [lindex $cp_S 15]  ;# bidir[12].pad @ 1x1 ordinal 15
lx_place $block PAD_SOUTH IO_SOUTH 16 [lindex $cp_S 16]  ;# bidir[13].pad @ 1x1 ordinal 16
lx_place $block PAD_SOUTH IO_SOUTH 17 3444.5000  ;# analog[0].pad (relocated analog, NOT 1x1-preserved)

# ---- IO_EAST (PAD_EAST) ----
# PAD_EAST list order == placement order below (idx -> location).
set cp_E [lx_1x1_curpos 5122 20 0]
lx_place $block PAD_EAST IO_EAST 0 [lindex $cp_E 0]  ;# dvdd_pads[0].pad @ 1x1 ordinal 0
lx_place $block PAD_EAST IO_EAST 1 [lindex $cp_E 1]  ;# dvss_pads[1].pad @ 1x1 ordinal 1
lx_place $block PAD_EAST IO_EAST 2 [lindex $cp_E 2]  ;# bidir[14].pad @ 1x1 ordinal 2
lx_place $block PAD_EAST IO_EAST 3 [lindex $cp_E 3]  ;# bidir[15].pad @ 1x1 ordinal 3
lx_place $block PAD_EAST IO_EAST 4 [lindex $cp_E 4]  ;# bidir[16].pad @ 1x1 ordinal 4
lx_place $block PAD_EAST IO_EAST 5 [lindex $cp_E 5]  ;# bidir[17].pad @ 1x1 ordinal 5
lx_place $block PAD_EAST IO_EAST 6 [lindex $cp_E 6]  ;# bidir[18].pad @ 1x1 ordinal 6
lx_place $block PAD_EAST IO_EAST 7 [lindex $cp_E 7]  ;# bidir[19].pad @ 1x1 ordinal 7
lx_place $block PAD_EAST IO_EAST 8 2072.0000  ;# analog[1].pad (relocated analog, NOT 1x1-preserved)

# PAD_NORTH: bare cut edge -- no pads

# ---- IO_WEST (PAD_WEST) ----
# PAD_WEST list order == placement order below (idx -> location).
set cp_W [lx_1x1_curpos 5122 20 0]
lx_place $block PAD_WEST IO_WEST 0 [lindex $cp_W 0]  ;# inputs[0].pad @ 1x1 ordinal 0
lx_place $block PAD_WEST IO_WEST 1 [lindex $cp_W 1]  ;# inputs[1].pad @ 1x1 ordinal 1
lx_place $block PAD_WEST IO_WEST 2 [lindex $cp_W 2]  ;# dvss_pads[2].pad @ 1x1 ordinal 2
lx_place $block PAD_WEST IO_WEST 3 [lindex $cp_W 3]  ;# dvdd_pads[1].pad @ 1x1 ordinal 3
lx_place $block PAD_WEST IO_WEST 4 [lindex $cp_W 4]  ;# inputs[2].pad @ 1x1 ordinal 4
lx_place $block PAD_WEST IO_WEST 5 [lindex $cp_W 5]  ;# inputs[3].pad @ 1x1 ordinal 5
lx_place $block PAD_WEST IO_WEST 6 [lindex $cp_W 6]  ;# inputs[4].pad @ 1x1 ordinal 6
lx_place $block PAD_WEST IO_WEST 7 [lindex $cp_W 7]  ;# inputs[5].pad @ 1x1 ordinal 7

puts "\[INFO\] Placing corner cells…"
place_corners $::env(PAD_CORNER)

puts "\[INFO\] Placing filler cells…"
place_io_fill -row IO_NORTH {*}$::env(PAD_FILLERS)
place_io_fill -row IO_SOUTH {*}$::env(PAD_FILLERS)
place_io_fill -row IO_WEST {*}$::env(PAD_FILLERS)
place_io_fill -row IO_EAST {*}$::env(PAD_FILLERS)

puts "\[INFO\] Connecting ring signals…"
connect_by_abutment

# Place io terminals (matches stock pad_cfg.tcl).
if { [info exists ::env(PAD_PLACE_IO_TERMINALS)] } {
    puts "\[INFO\] Placing I/O terminals…"
    foreach side {PAD_SOUTH PAD_EAST PAD_NORTH PAD_WEST} {
        if { ![info exists ::env($side)] } { continue }
        foreach inst_name $::env($side) {
            if { [set inst [$block findInst $inst_name]] == "NULL" } { continue }
            set master_name [[$inst getMaster] getName]
            foreach master_pin $::env(PAD_PLACE_IO_TERMINALS) {
                set parts [split $master_pin /]
                if {$master_name == [lindex $parts 0]} {
                    place_io_terminals $inst_name/[lindex $parts 1]
                    break
                }
            }
        }
    }
}

puts "\[INFO\] Removing I/O rows…"
remove_io_rows
