# AUTOGENERATED by scripts/generate_exact_3side_configs.py -- DO NOT EDIT.
#
# Exact-pad PAD_CFG for slot_1x0p5_3side_exact.
#
# This replays LibreLane common/pad_cfg.tcl's cur_pos arithmetic
# using slot_1x1's die dimension + full per-edge pad count, then
# issues, for every retained pad, the identical place_pad -location
# call the real slot_1x1 build issued for that 1x1 ordinal -- giving
# byte-identical pad coordinates.  (S/N: 1x1 die=3932 n=17; E/W:
# 1x1 die=5122 n=20.  Constants from the PDK IO config:
# PAD_EDGE_SPACING=26, PAD_FAKE_CORNER_SITE=355, PAD_FAKE_SITE=0.1.)

source $::env(SCRIPTS_DIR)/openroad/common/set_global_connections.tcl
set_global_connections

puts "\[INFO\] Generating EXACT-pad padring for 1x0p5_3side_exact…"

make_io_sites \
    -horizontal_site $::env(PAD_SITE_NAME) \
    -vertical_site $::env(PAD_SITE_NAME) \
    -corner_site $::env(PAD_CORNER_SITE_NAME) \
    -offset $::env(PAD_EDGE_SPACING)

set block [ord::get_db_block]

# ---- slot_1x1 cur_pos replay helper ---------------------------------
# Reproduces pad_cfg.tcl lines 73-131 for a slot_1x1 edge and returns
# the list of cur_pos values (one per 1x1 ordinal, all pads 75um).
proc lx_1x1_curpos {die_dim n_pads is_horizontal} {
    set es $::env(PAD_EDGE_SPACING)
    if {$is_horizontal} {
        set corner $::env(PAD_FAKE_CORNER_SITE_WIDTH)
    } else {
        set corner $::env(PAD_FAKE_CORNER_SITE_HEIGHT)
    }
    set site $::env(PAD_FAKE_SITE_WIDTH)
    set pad_w 75
    set side_width [expr {$die_dim - $es*2 - $corner*2}]
    set sum_w [expr {$pad_w * $n_pads}]
    set fill [expr {$side_width - $sum_w}]
    set sbp [expr {$fill / ($n_pads + 1)}]
    set sbp1 [expr {floor($sbp / $site) * $site}]
    set sspace [expr {($fill - $sbp1*($n_pads-1)) / 2.0}]
    set cur [expr {$sspace + $es + $corner}]
    set out {}
    for {set i 0} {$i < $n_pads} {incr i} {
        lappend out $cur
        set cur [expr {$cur + $sbp1 + $pad_w}]
    }
    return $out
}

# Place pad #idx of $::env($side) (the SAME resolved instance list
# stock pad_cfg.tcl iterates -- avoids any name re-escaping) at the
# given along-edge location.
proc lx_place {block side row idx loc} {
    set inst [lindex $::env($side) $idx]
    if { [set i [$block findInst $inst]] == "NULL" } {
        puts stderr "\[ERROR\] exact PAD_CFG: $side\[$idx\] ($inst) not found"
        exit 1
    }
    place_pad -row $row -location $loc \
        -master [[$i getMaster] getName] $inst
}

# ---- IO_SOUTH (PAD_SOUTH) ----
# PAD_SOUTH list order == placement order below (idx -> location).
set cp_S [lx_1x1_curpos 3932 17 1]
lx_place $block PAD_SOUTH IO_SOUTH 0 [lindex $cp_S 0]  ;# clk_pad @ 1x1 ordinal 0
lx_place $block PAD_SOUTH IO_SOUTH 1 [lindex $cp_S 1]  ;# rst_n_pad @ 1x1 ordinal 1
lx_place $block PAD_SOUTH IO_SOUTH 2 [lindex $cp_S 2]  ;# bidir[0].pad @ 1x1 ordinal 2
lx_place $block PAD_SOUTH IO_SOUTH 3 [lindex $cp_S 3]  ;# bidir[1].pad @ 1x1 ordinal 3
lx_place $block PAD_SOUTH IO_SOUTH 4 [lindex $cp_S 4]  ;# bidir[2].pad @ 1x1 ordinal 4
lx_place $block PAD_SOUTH IO_SOUTH 5 [lindex $cp_S 5]  ;# bidir[3].pad @ 1x1 ordinal 5
lx_place $block PAD_SOUTH IO_SOUTH 6 [lindex $cp_S 6]  ;# bidir[4].pad @ 1x1 ordinal 6
lx_place $block PAD_SOUTH IO_SOUTH 7 [lindex $cp_S 7]  ;# bidir[5].pad @ 1x1 ordinal 7
lx_place $block PAD_SOUTH IO_SOUTH 8 [lindex $cp_S 8]  ;# dvss_pads[0].pad @ 1x1 ordinal 8
lx_place $block PAD_SOUTH IO_SOUTH 9 [lindex $cp_S 9]  ;# bidir[6].pad @ 1x1 ordinal 9
lx_place $block PAD_SOUTH IO_SOUTH 10 [lindex $cp_S 10]  ;# bidir[7].pad @ 1x1 ordinal 10
lx_place $block PAD_SOUTH IO_SOUTH 11 [lindex $cp_S 11]  ;# bidir[8].pad @ 1x1 ordinal 11
lx_place $block PAD_SOUTH IO_SOUTH 12 [lindex $cp_S 12]  ;# bidir[9].pad @ 1x1 ordinal 12
lx_place $block PAD_SOUTH IO_SOUTH 13 [lindex $cp_S 13]  ;# bidir[10].pad @ 1x1 ordinal 13
lx_place $block PAD_SOUTH IO_SOUTH 14 [lindex $cp_S 14]  ;# bidir[11].pad @ 1x1 ordinal 14
lx_place $block PAD_SOUTH IO_SOUTH 15 [lindex $cp_S 15]  ;# bidir[12].pad @ 1x1 ordinal 15
lx_place $block PAD_SOUTH IO_SOUTH 16 [lindex $cp_S 16]  ;# bidir[13].pad @ 1x1 ordinal 16

# ---- IO_EAST (PAD_EAST) ----
# PAD_EAST list order == placement order below (idx -> location).
set cp_E [lx_1x1_curpos 5122 20 0]
lx_place $block PAD_EAST IO_EAST 0 [lindex $cp_E 0]  ;# dvdd_pads[0].pad @ 1x1 ordinal 0
lx_place $block PAD_EAST IO_EAST 1 [lindex $cp_E 1]  ;# dvss_pads[1].pad @ 1x1 ordinal 1
lx_place $block PAD_EAST IO_EAST 2 [lindex $cp_E 2]  ;# bidir[14].pad @ 1x1 ordinal 2
lx_place $block PAD_EAST IO_EAST 3 [lindex $cp_E 3]  ;# bidir[15].pad @ 1x1 ordinal 3
lx_place $block PAD_EAST IO_EAST 4 [lindex $cp_E 4]  ;# bidir[16].pad @ 1x1 ordinal 4
lx_place $block PAD_EAST IO_EAST 5 [lindex $cp_E 5]  ;# bidir[17].pad @ 1x1 ordinal 5
lx_place $block PAD_EAST IO_EAST 6 [lindex $cp_E 6]  ;# bidir[18].pad @ 1x1 ordinal 6
lx_place $block PAD_EAST IO_EAST 7 [lindex $cp_E 7]  ;# bidir[19].pad @ 1x1 ordinal 7
lx_place $block PAD_EAST IO_EAST 8 [lindex $cp_E 8]  ;# dvdd_pads[1].pad @ 1x1 ordinal 8
lx_place $block PAD_EAST IO_EAST 9 [lindex $cp_E 9]  ;# dvss_pads[2].pad @ 1x1 ordinal 9

# PAD_NORTH: bare cut edge -- no pads

# ---- IO_WEST (PAD_WEST) ----
# PAD_WEST list order == placement order below (idx -> location).
set cp_W [lx_1x1_curpos 5122 20 0]
lx_place $block PAD_WEST IO_WEST 0 [lindex $cp_W 0]  ;# inputs[0].pad @ 1x1 ordinal 0
lx_place $block PAD_WEST IO_WEST 1 [lindex $cp_W 1]  ;# inputs[1].pad @ 1x1 ordinal 1
lx_place $block PAD_WEST IO_WEST 2 [lindex $cp_W 2]  ;# dvss_pads[3].pad @ 1x1 ordinal 2
lx_place $block PAD_WEST IO_WEST 3 [lindex $cp_W 3]  ;# dvdd_pads[2].pad @ 1x1 ordinal 3
lx_place $block PAD_WEST IO_WEST 4 [lindex $cp_W 4]  ;# inputs[2].pad @ 1x1 ordinal 4
lx_place $block PAD_WEST IO_WEST 5 [lindex $cp_W 5]  ;# inputs[3].pad @ 1x1 ordinal 5
lx_place $block PAD_WEST IO_WEST 6 [lindex $cp_W 6]  ;# inputs[4].pad @ 1x1 ordinal 6
lx_place $block PAD_WEST IO_WEST 7 [lindex $cp_W 7]  ;# inputs[5].pad @ 1x1 ordinal 7
lx_place $block PAD_WEST IO_WEST 8 [lindex $cp_W 8]  ;# dvss_pads[4].pad @ 1x1 ordinal 8
lx_place $block PAD_WEST IO_WEST 9 [lindex $cp_W 9]  ;# dvdd_pads[3].pad @ 1x1 ordinal 9

puts "\[INFO\] Placing corner cells…"
place_corners $::env(PAD_CORNER)

# Drop the bare-edge corner cell(s): no IO row abuts them, they would
# just be isolated structures on the bare cut edge.
set _bare_edges [list "north"]
set _xmid [expr {([lindex $::env(DIE_AREA) 0] + [lindex $::env(DIE_AREA) 2]) / 2.0}]
set _ymid [expr {([lindex $::env(DIE_AREA) 1] + [lindex $::env(DIE_AREA) 3]) / 2.0}]
set _units [$block getDefUnits]
# Identify bare-edge corner cells AND remember their bbox + side BEFORE
# destroying them -- the bbox is the freed silicon strip we will later
# fill with IO row fillers so the row visually extends to the die edge.
set _bare_corner_data [list]
foreach _inst [$block getInsts] {
    if { [[$_inst getMaster] getName] ne $::env(PAD_CORNER) } { continue }
    set _bb [$_inst getBBox]
    set _cx [expr {([$_bb xMin] + [$_bb xMax]) / 2.0 / $_units}]
    set _cy [expr {([$_bb yMin] + [$_bb yMax]) / 2.0 / $_units}]
    set _is_north [expr {$_cy > $_ymid}]
    set _is_east  [expr {$_cx > $_xmid}]
    set _drop 0
    foreach _edge $_bare_edges {
        switch -- $_edge {
            east  { if { $_is_east }      { set _drop 1 } }
            west  { if { ! $_is_east }    { set _drop 1 } }
            north { if { $_is_north }     { set _drop 1 } }
            south { if { ! $_is_north }   { set _drop 1 } }
        }
        if { $_drop } { break }
    }
    if { $_drop } {
        lappend _bare_corner_data [list [$_bb xMin] [$_bb yMin] \
            [$_bb xMax] [$_bb yMax] $_is_north $_inst]
    }
}
set _destroyed 0
foreach _data $_bare_corner_data {
    odb::dbInst_destroy [lindex $_data 5]
    incr _destroyed
}
puts "\[INFO\] Bare-edge corner cleanup (bare: $_bare_edges): destroyed $_destroyed corner cell(s)."

# Extend the adjacent IO row over the freed corner X strip by creating a
# SUPPLEMENTAL dbRow at the corner location with the same site / orient /
# direction as the original row, then letting `place_io_fill` populate it.
# This is preferable to dbInst_create'ing fillers manually because:
#  - `place_io_fill` produces site-aligned cells the row-walking power
#    chain understands;
#  - `connect_by_abutment` (called below) walks dbRows by name and would
#    miss standalone cells outside any row, leading to Magic Illegal
#    Overlap errors at DRC time (~357-1430 per build observed).
# We name the new rows IO_<side>_EXT_<x> so they look like ordinary IO rows
# to place_io_fill but don't collide with the original row name.
set _ext_row_names [list]
# Pre-iterate rows once; dbBlock has no findRow, just getRows.
set _rows_by_name [dict create]
foreach _r [$block getRows] {
    dict set _rows_by_name [$_r getName] $_r
}
foreach _data $_bare_corner_data {
    lassign $_data _cxlo _cylo _cxhi _cyhi _is_north _inst
    set _is_east [expr {(($_cxlo + $_cxhi) / 2.0 / $_units) > $_xmid}]
    # Decide which adjacent row of this destroyed corner is KEPT (not bare).
    # NS side is the corner's north/south side; EW side is its east/west side.
    set _ns_side [expr {$_is_north ? "north" : "south"}]
    set _ew_side [expr {$_is_east  ? "east"  : "west"}]
    set _ns_bare [expr {[lsearch -exact $_bare_edges $_ns_side] >= 0}]
    set _ew_bare [expr {[lsearch -exact $_bare_edges $_ew_side] >= 0}]
    # Prefer horizontal (N/S) extension when the kept-adjacent N/S row
    # exists (matches the original IO_SOUTH east-extending behaviour);
    # fall back to vertical (E/W) extension for bare-N/S configs where
    # only the perpendicular row is kept.
    set _row_name ""
    set _is_horizontal 1
    if {!$_ns_bare} {
        set _row_name "IO_[string toupper $_ns_side]"
        set _is_horizontal 1
    } elseif {!$_ew_bare} {
        set _row_name "IO_[string toupper $_ew_side]"
        set _is_horizontal 0
    } else {
        # Both adjacents bare (e.g. NE corner of bare-NE quarter slot):
        # no IO row exists to extend — leave the corner area empty.
        puts "\[INFO\] Corner at x=${_cxlo}-${_cxhi} y=${_cylo}-${_cyhi}: both adjacent edges bare, no extension possible."
        continue
    }
    if {![dict exists $_rows_by_name $_row_name]} { continue }
    set _row [dict get $_rows_by_name $_row_name]
    set _site [$_row getSite]
    set _row_bb [$_row getBBox]
    set _row_orient [$_row getOrient]
    set _row_dir [$_row getDirection]
    set _site_w [$_site getWidth]
    if {$_is_horizontal} {
        # Horizontal row extension: place a new row along the corner's X
        # strip at the kept row's Y origin. Cells stride along X using
        # the site's width (== PAD_FAKE_SITE_WIDTH for gf180mcu).
        set _ext_origin_x $_cxlo
        set _ext_origin_y [$_row_bb yMin]
        set _ext_axis_len [expr {$_cxhi - $_cxlo}]
    } else {
        # Vertical row extension: place a new row along the corner's Y
        # strip at the kept row's X origin. dbRow_create's 'spacing'
        # parameter is the per-site stride along the row direction;
        # OpenROAD uses site getWidth() for that for both H and V rows
        # (the row's direction field tells the placer which axis).
        set _ext_origin_x [$_row_bb xMin]
        set _ext_origin_y $_cylo
        set _ext_axis_len [expr {$_cyhi - $_cylo}]
    }
    set _num_sites [expr {$_ext_axis_len / $_site_w}]
    if {$_num_sites <= 0} { continue }
    # Unique row name per corner to avoid collision with original IO rows.
    set _ext_name "${_row_name}_EXT_${_ext_origin_x}_${_ext_origin_y}"
    puts "\[INFO\]   ext-row $_ext_name origin=(${_ext_origin_x},${_ext_origin_y}) site=[$_site getName] sites=$_num_sites dir=$_row_dir orient=$_row_orient"
    odb::dbRow_create $block $_ext_name $_site $_ext_origin_x $_ext_origin_y \
        $_row_orient $_row_dir $_num_sites $_site_w
    lappend _ext_row_names $_ext_name
}
puts "\[INFO\] Bare-edge corner fill: created [llength $_ext_row_names] extension row(s) to fill via place_io_fill."

puts "\[INFO\] Placing filler cells…"
# Skip `place_io_fill` on bare-edge rows: no pads + no corners on
# that row means filler cells would be the only content, which is
# pure waste on a cut edge.
foreach _row {IO_NORTH IO_SOUTH IO_WEST IO_EAST} {
    set _edge_lc [string tolower [string range $_row 3 end]]
    if { [lsearch -exact $_bare_edges $_edge_lc] >= 0 } {
        puts "\[INFO\] Skipping place_io_fill on $_row (bare cut edge)"
        continue
    }
    place_io_fill -row $_row {*}$::env(PAD_FILLERS)
}
# Fill the corner-extension rows we created above. Doing this AFTER the
# main rows are filled means the existing IO_NORTH/IO_SOUTH cells are now
# in place at the corner-adjacent X, so place_io_fill's adjacency-aware
# packing knows where to start (just east of the row's last filler).
foreach _ext $_ext_row_names {
    puts "\[INFO\] Filling extension row $_ext"
    place_io_fill -row $_ext {*}$::env(PAD_FILLERS)
}

puts "\[INFO\] Connecting ring signals…"
connect_by_abutment

# Place io terminals (matches stock pad_cfg.tcl).
if { [info exists ::env(PAD_PLACE_IO_TERMINALS)] } {
    puts "\[INFO\] Placing I/O terminals…"
    foreach side {PAD_SOUTH PAD_EAST PAD_NORTH PAD_WEST} {
        if { ![info exists ::env($side)] } { continue }
        foreach inst_name $::env($side) {
            if { [set inst [$block findInst $inst_name]] == "NULL" } { continue }
            set master_name [[$inst getMaster] getName]
            foreach master_pin $::env(PAD_PLACE_IO_TERMINALS) {
                set parts [split $master_pin /]
                if {$master_name == [lindex $parts 0]} {
                    place_io_terminals $inst_name/[lindex $parts 1]
                    break
                }
            }
        }
    }
}

puts "\[INFO\] Removing I/O rows…"
remove_io_rows
