// SRAM Array Module
// Generated by sram-forge
// Chip: gf180mcu_ic_1x1_sram_u8b24k
// 24KB SRAM (8-bit x 24K) for 1x1 wafer.space slot
// Configuration:
//   SRAM Macro: gf180mcu_fd_ip_sram__sram512x8m8wm1
//   Total SRAMs: 48
//   Total Words: 24576
//   Address Bits: 15
//   Data Width: 8
//   Output Routing: mux

module gf180mcu_ic_1x1_sram_u8b24k_sram_array (
    input  wire                    clk,
    input  wire                    rst_n,
    input  wire                    ce_n,      // Chip enable (active low)
    input  wire                    we_n,      // Write enable (active low)
    input  wire [14:0]       addr,      // Address bus
    input  wire [7:0]        din,       // Data input
    output wire [7:0]        dout       // Data output
);

    // Address decoding
    // Upper bits select SRAM, lower bits address within SRAM
    wire [5:0] sram_sel;
    wire [8:0] sram_addr;

    assign sram_sel = addr[14:9];
    assign sram_addr = addr[8:0];

    // SRAM enable signals (directly from address decoder)
    wire [47:0] sram_ce_n;
    assign sram_ce_n[0] = ce_n | (sram_sel != 6'd0);
    assign sram_ce_n[1] = ce_n | (sram_sel != 6'd1);
    assign sram_ce_n[2] = ce_n | (sram_sel != 6'd2);
    assign sram_ce_n[3] = ce_n | (sram_sel != 6'd3);
    assign sram_ce_n[4] = ce_n | (sram_sel != 6'd4);
    assign sram_ce_n[5] = ce_n | (sram_sel != 6'd5);
    assign sram_ce_n[6] = ce_n | (sram_sel != 6'd6);
    assign sram_ce_n[7] = ce_n | (sram_sel != 6'd7);
    assign sram_ce_n[8] = ce_n | (sram_sel != 6'd8);
    assign sram_ce_n[9] = ce_n | (sram_sel != 6'd9);
    assign sram_ce_n[10] = ce_n | (sram_sel != 6'd10);
    assign sram_ce_n[11] = ce_n | (sram_sel != 6'd11);
    assign sram_ce_n[12] = ce_n | (sram_sel != 6'd12);
    assign sram_ce_n[13] = ce_n | (sram_sel != 6'd13);
    assign sram_ce_n[14] = ce_n | (sram_sel != 6'd14);
    assign sram_ce_n[15] = ce_n | (sram_sel != 6'd15);
    assign sram_ce_n[16] = ce_n | (sram_sel != 6'd16);
    assign sram_ce_n[17] = ce_n | (sram_sel != 6'd17);
    assign sram_ce_n[18] = ce_n | (sram_sel != 6'd18);
    assign sram_ce_n[19] = ce_n | (sram_sel != 6'd19);
    assign sram_ce_n[20] = ce_n | (sram_sel != 6'd20);
    assign sram_ce_n[21] = ce_n | (sram_sel != 6'd21);
    assign sram_ce_n[22] = ce_n | (sram_sel != 6'd22);
    assign sram_ce_n[23] = ce_n | (sram_sel != 6'd23);
    assign sram_ce_n[24] = ce_n | (sram_sel != 6'd24);
    assign sram_ce_n[25] = ce_n | (sram_sel != 6'd25);
    assign sram_ce_n[26] = ce_n | (sram_sel != 6'd26);
    assign sram_ce_n[27] = ce_n | (sram_sel != 6'd27);
    assign sram_ce_n[28] = ce_n | (sram_sel != 6'd28);
    assign sram_ce_n[29] = ce_n | (sram_sel != 6'd29);
    assign sram_ce_n[30] = ce_n | (sram_sel != 6'd30);
    assign sram_ce_n[31] = ce_n | (sram_sel != 6'd31);
    assign sram_ce_n[32] = ce_n | (sram_sel != 6'd32);
    assign sram_ce_n[33] = ce_n | (sram_sel != 6'd33);
    assign sram_ce_n[34] = ce_n | (sram_sel != 6'd34);
    assign sram_ce_n[35] = ce_n | (sram_sel != 6'd35);
    assign sram_ce_n[36] = ce_n | (sram_sel != 6'd36);
    assign sram_ce_n[37] = ce_n | (sram_sel != 6'd37);
    assign sram_ce_n[38] = ce_n | (sram_sel != 6'd38);
    assign sram_ce_n[39] = ce_n | (sram_sel != 6'd39);
    assign sram_ce_n[40] = ce_n | (sram_sel != 6'd40);
    assign sram_ce_n[41] = ce_n | (sram_sel != 6'd41);
    assign sram_ce_n[42] = ce_n | (sram_sel != 6'd42);
    assign sram_ce_n[43] = ce_n | (sram_sel != 6'd43);
    assign sram_ce_n[44] = ce_n | (sram_sel != 6'd44);
    assign sram_ce_n[45] = ce_n | (sram_sel != 6'd45);
    assign sram_ce_n[46] = ce_n | (sram_sel != 6'd46);
    assign sram_ce_n[47] = ce_n | (sram_sel != 6'd47);

    // SRAM output buses
    wire [7:0] sram_dout_0;
    wire [7:0] sram_dout_1;
    wire [7:0] sram_dout_2;
    wire [7:0] sram_dout_3;
    wire [7:0] sram_dout_4;
    wire [7:0] sram_dout_5;
    wire [7:0] sram_dout_6;
    wire [7:0] sram_dout_7;
    wire [7:0] sram_dout_8;
    wire [7:0] sram_dout_9;
    wire [7:0] sram_dout_10;
    wire [7:0] sram_dout_11;
    wire [7:0] sram_dout_12;
    wire [7:0] sram_dout_13;
    wire [7:0] sram_dout_14;
    wire [7:0] sram_dout_15;
    wire [7:0] sram_dout_16;
    wire [7:0] sram_dout_17;
    wire [7:0] sram_dout_18;
    wire [7:0] sram_dout_19;
    wire [7:0] sram_dout_20;
    wire [7:0] sram_dout_21;
    wire [7:0] sram_dout_22;
    wire [7:0] sram_dout_23;
    wire [7:0] sram_dout_24;
    wire [7:0] sram_dout_25;
    wire [7:0] sram_dout_26;
    wire [7:0] sram_dout_27;
    wire [7:0] sram_dout_28;
    wire [7:0] sram_dout_29;
    wire [7:0] sram_dout_30;
    wire [7:0] sram_dout_31;
    wire [7:0] sram_dout_32;
    wire [7:0] sram_dout_33;
    wire [7:0] sram_dout_34;
    wire [7:0] sram_dout_35;
    wire [7:0] sram_dout_36;
    wire [7:0] sram_dout_37;
    wire [7:0] sram_dout_38;
    wire [7:0] sram_dout_39;
    wire [7:0] sram_dout_40;
    wire [7:0] sram_dout_41;
    wire [7:0] sram_dout_42;
    wire [7:0] sram_dout_43;
    wire [7:0] sram_dout_44;
    wire [7:0] sram_dout_45;
    wire [7:0] sram_dout_46;
    wire [7:0] sram_dout_47;

    // SRAM macro instantiations
    gf180mcu_fd_ip_sram__sram512x8m8wm1 sram_0 (
        .CLK(clk),
        .CEN(sram_ce_n[0]),
        .GWEN(we_n),
        .WEN(8'b0),  // All bits written when GWEN active
        .A(sram_addr),
        .D(din),
        .Q(sram_dout_0)
    );

    gf180mcu_fd_ip_sram__sram512x8m8wm1 sram_1 (
        .CLK(clk),
        .CEN(sram_ce_n[1]),
        .GWEN(we_n),
        .WEN(8'b0),  // All bits written when GWEN active
        .A(sram_addr),
        .D(din),
        .Q(sram_dout_1)
    );

    gf180mcu_fd_ip_sram__sram512x8m8wm1 sram_2 (
        .CLK(clk),
        .CEN(sram_ce_n[2]),
        .GWEN(we_n),
        .WEN(8'b0),  // All bits written when GWEN active
        .A(sram_addr),
        .D(din),
        .Q(sram_dout_2)
    );

    gf180mcu_fd_ip_sram__sram512x8m8wm1 sram_3 (
        .CLK(clk),
        .CEN(sram_ce_n[3]),
        .GWEN(we_n),
        .WEN(8'b0),  // All bits written when GWEN active
        .A(sram_addr),
        .D(din),
        .Q(sram_dout_3)
    );

    gf180mcu_fd_ip_sram__sram512x8m8wm1 sram_4 (
        .CLK(clk),
        .CEN(sram_ce_n[4]),
        .GWEN(we_n),
        .WEN(8'b0),  // All bits written when GWEN active
        .A(sram_addr),
        .D(din),
        .Q(sram_dout_4)
    );

    gf180mcu_fd_ip_sram__sram512x8m8wm1 sram_5 (
        .CLK(clk),
        .CEN(sram_ce_n[5]),
        .GWEN(we_n),
        .WEN(8'b0),  // All bits written when GWEN active
        .A(sram_addr),
        .D(din),
        .Q(sram_dout_5)
    );

    gf180mcu_fd_ip_sram__sram512x8m8wm1 sram_6 (
        .CLK(clk),
        .CEN(sram_ce_n[6]),
        .GWEN(we_n),
        .WEN(8'b0),  // All bits written when GWEN active
        .A(sram_addr),
        .D(din),
        .Q(sram_dout_6)
    );

    gf180mcu_fd_ip_sram__sram512x8m8wm1 sram_7 (
        .CLK(clk),
        .CEN(sram_ce_n[7]),
        .GWEN(we_n),
        .WEN(8'b0),  // All bits written when GWEN active
        .A(sram_addr),
        .D(din),
        .Q(sram_dout_7)
    );

    gf180mcu_fd_ip_sram__sram512x8m8wm1 sram_8 (
        .CLK(clk),
        .CEN(sram_ce_n[8]),
        .GWEN(we_n),
        .WEN(8'b0),  // All bits written when GWEN active
        .A(sram_addr),
        .D(din),
        .Q(sram_dout_8)
    );

    gf180mcu_fd_ip_sram__sram512x8m8wm1 sram_9 (
        .CLK(clk),
        .CEN(sram_ce_n[9]),
        .GWEN(we_n),
        .WEN(8'b0),  // All bits written when GWEN active
        .A(sram_addr),
        .D(din),
        .Q(sram_dout_9)
    );

    gf180mcu_fd_ip_sram__sram512x8m8wm1 sram_10 (
        .CLK(clk),
        .CEN(sram_ce_n[10]),
        .GWEN(we_n),
        .WEN(8'b0),  // All bits written when GWEN active
        .A(sram_addr),
        .D(din),
        .Q(sram_dout_10)
    );

    gf180mcu_fd_ip_sram__sram512x8m8wm1 sram_11 (
        .CLK(clk),
        .CEN(sram_ce_n[11]),
        .GWEN(we_n),
        .WEN(8'b0),  // All bits written when GWEN active
        .A(sram_addr),
        .D(din),
        .Q(sram_dout_11)
    );

    gf180mcu_fd_ip_sram__sram512x8m8wm1 sram_12 (
        .CLK(clk),
        .CEN(sram_ce_n[12]),
        .GWEN(we_n),
        .WEN(8'b0),  // All bits written when GWEN active
        .A(sram_addr),
        .D(din),
        .Q(sram_dout_12)
    );

    gf180mcu_fd_ip_sram__sram512x8m8wm1 sram_13 (
        .CLK(clk),
        .CEN(sram_ce_n[13]),
        .GWEN(we_n),
        .WEN(8'b0),  // All bits written when GWEN active
        .A(sram_addr),
        .D(din),
        .Q(sram_dout_13)
    );

    gf180mcu_fd_ip_sram__sram512x8m8wm1 sram_14 (
        .CLK(clk),
        .CEN(sram_ce_n[14]),
        .GWEN(we_n),
        .WEN(8'b0),  // All bits written when GWEN active
        .A(sram_addr),
        .D(din),
        .Q(sram_dout_14)
    );

    gf180mcu_fd_ip_sram__sram512x8m8wm1 sram_15 (
        .CLK(clk),
        .CEN(sram_ce_n[15]),
        .GWEN(we_n),
        .WEN(8'b0),  // All bits written when GWEN active
        .A(sram_addr),
        .D(din),
        .Q(sram_dout_15)
    );

    gf180mcu_fd_ip_sram__sram512x8m8wm1 sram_16 (
        .CLK(clk),
        .CEN(sram_ce_n[16]),
        .GWEN(we_n),
        .WEN(8'b0),  // All bits written when GWEN active
        .A(sram_addr),
        .D(din),
        .Q(sram_dout_16)
    );

    gf180mcu_fd_ip_sram__sram512x8m8wm1 sram_17 (
        .CLK(clk),
        .CEN(sram_ce_n[17]),
        .GWEN(we_n),
        .WEN(8'b0),  // All bits written when GWEN active
        .A(sram_addr),
        .D(din),
        .Q(sram_dout_17)
    );

    gf180mcu_fd_ip_sram__sram512x8m8wm1 sram_18 (
        .CLK(clk),
        .CEN(sram_ce_n[18]),
        .GWEN(we_n),
        .WEN(8'b0),  // All bits written when GWEN active
        .A(sram_addr),
        .D(din),
        .Q(sram_dout_18)
    );

    gf180mcu_fd_ip_sram__sram512x8m8wm1 sram_19 (
        .CLK(clk),
        .CEN(sram_ce_n[19]),
        .GWEN(we_n),
        .WEN(8'b0),  // All bits written when GWEN active
        .A(sram_addr),
        .D(din),
        .Q(sram_dout_19)
    );

    gf180mcu_fd_ip_sram__sram512x8m8wm1 sram_20 (
        .CLK(clk),
        .CEN(sram_ce_n[20]),
        .GWEN(we_n),
        .WEN(8'b0),  // All bits written when GWEN active
        .A(sram_addr),
        .D(din),
        .Q(sram_dout_20)
    );

    gf180mcu_fd_ip_sram__sram512x8m8wm1 sram_21 (
        .CLK(clk),
        .CEN(sram_ce_n[21]),
        .GWEN(we_n),
        .WEN(8'b0),  // All bits written when GWEN active
        .A(sram_addr),
        .D(din),
        .Q(sram_dout_21)
    );

    gf180mcu_fd_ip_sram__sram512x8m8wm1 sram_22 (
        .CLK(clk),
        .CEN(sram_ce_n[22]),
        .GWEN(we_n),
        .WEN(8'b0),  // All bits written when GWEN active
        .A(sram_addr),
        .D(din),
        .Q(sram_dout_22)
    );

    gf180mcu_fd_ip_sram__sram512x8m8wm1 sram_23 (
        .CLK(clk),
        .CEN(sram_ce_n[23]),
        .GWEN(we_n),
        .WEN(8'b0),  // All bits written when GWEN active
        .A(sram_addr),
        .D(din),
        .Q(sram_dout_23)
    );

    gf180mcu_fd_ip_sram__sram512x8m8wm1 sram_24 (
        .CLK(clk),
        .CEN(sram_ce_n[24]),
        .GWEN(we_n),
        .WEN(8'b0),  // All bits written when GWEN active
        .A(sram_addr),
        .D(din),
        .Q(sram_dout_24)
    );

    gf180mcu_fd_ip_sram__sram512x8m8wm1 sram_25 (
        .CLK(clk),
        .CEN(sram_ce_n[25]),
        .GWEN(we_n),
        .WEN(8'b0),  // All bits written when GWEN active
        .A(sram_addr),
        .D(din),
        .Q(sram_dout_25)
    );

    gf180mcu_fd_ip_sram__sram512x8m8wm1 sram_26 (
        .CLK(clk),
        .CEN(sram_ce_n[26]),
        .GWEN(we_n),
        .WEN(8'b0),  // All bits written when GWEN active
        .A(sram_addr),
        .D(din),
        .Q(sram_dout_26)
    );

    gf180mcu_fd_ip_sram__sram512x8m8wm1 sram_27 (
        .CLK(clk),
        .CEN(sram_ce_n[27]),
        .GWEN(we_n),
        .WEN(8'b0),  // All bits written when GWEN active
        .A(sram_addr),
        .D(din),
        .Q(sram_dout_27)
    );

    gf180mcu_fd_ip_sram__sram512x8m8wm1 sram_28 (
        .CLK(clk),
        .CEN(sram_ce_n[28]),
        .GWEN(we_n),
        .WEN(8'b0),  // All bits written when GWEN active
        .A(sram_addr),
        .D(din),
        .Q(sram_dout_28)
    );

    gf180mcu_fd_ip_sram__sram512x8m8wm1 sram_29 (
        .CLK(clk),
        .CEN(sram_ce_n[29]),
        .GWEN(we_n),
        .WEN(8'b0),  // All bits written when GWEN active
        .A(sram_addr),
        .D(din),
        .Q(sram_dout_29)
    );

    gf180mcu_fd_ip_sram__sram512x8m8wm1 sram_30 (
        .CLK(clk),
        .CEN(sram_ce_n[30]),
        .GWEN(we_n),
        .WEN(8'b0),  // All bits written when GWEN active
        .A(sram_addr),
        .D(din),
        .Q(sram_dout_30)
    );

    gf180mcu_fd_ip_sram__sram512x8m8wm1 sram_31 (
        .CLK(clk),
        .CEN(sram_ce_n[31]),
        .GWEN(we_n),
        .WEN(8'b0),  // All bits written when GWEN active
        .A(sram_addr),
        .D(din),
        .Q(sram_dout_31)
    );

    gf180mcu_fd_ip_sram__sram512x8m8wm1 sram_32 (
        .CLK(clk),
        .CEN(sram_ce_n[32]),
        .GWEN(we_n),
        .WEN(8'b0),  // All bits written when GWEN active
        .A(sram_addr),
        .D(din),
        .Q(sram_dout_32)
    );

    gf180mcu_fd_ip_sram__sram512x8m8wm1 sram_33 (
        .CLK(clk),
        .CEN(sram_ce_n[33]),
        .GWEN(we_n),
        .WEN(8'b0),  // All bits written when GWEN active
        .A(sram_addr),
        .D(din),
        .Q(sram_dout_33)
    );

    gf180mcu_fd_ip_sram__sram512x8m8wm1 sram_34 (
        .CLK(clk),
        .CEN(sram_ce_n[34]),
        .GWEN(we_n),
        .WEN(8'b0),  // All bits written when GWEN active
        .A(sram_addr),
        .D(din),
        .Q(sram_dout_34)
    );

    gf180mcu_fd_ip_sram__sram512x8m8wm1 sram_35 (
        .CLK(clk),
        .CEN(sram_ce_n[35]),
        .GWEN(we_n),
        .WEN(8'b0),  // All bits written when GWEN active
        .A(sram_addr),
        .D(din),
        .Q(sram_dout_35)
    );

    gf180mcu_fd_ip_sram__sram512x8m8wm1 sram_36 (
        .CLK(clk),
        .CEN(sram_ce_n[36]),
        .GWEN(we_n),
        .WEN(8'b0),  // All bits written when GWEN active
        .A(sram_addr),
        .D(din),
        .Q(sram_dout_36)
    );

    gf180mcu_fd_ip_sram__sram512x8m8wm1 sram_37 (
        .CLK(clk),
        .CEN(sram_ce_n[37]),
        .GWEN(we_n),
        .WEN(8'b0),  // All bits written when GWEN active
        .A(sram_addr),
        .D(din),
        .Q(sram_dout_37)
    );

    gf180mcu_fd_ip_sram__sram512x8m8wm1 sram_38 (
        .CLK(clk),
        .CEN(sram_ce_n[38]),
        .GWEN(we_n),
        .WEN(8'b0),  // All bits written when GWEN active
        .A(sram_addr),
        .D(din),
        .Q(sram_dout_38)
    );

    gf180mcu_fd_ip_sram__sram512x8m8wm1 sram_39 (
        .CLK(clk),
        .CEN(sram_ce_n[39]),
        .GWEN(we_n),
        .WEN(8'b0),  // All bits written when GWEN active
        .A(sram_addr),
        .D(din),
        .Q(sram_dout_39)
    );

    gf180mcu_fd_ip_sram__sram512x8m8wm1 sram_40 (
        .CLK(clk),
        .CEN(sram_ce_n[40]),
        .GWEN(we_n),
        .WEN(8'b0),  // All bits written when GWEN active
        .A(sram_addr),
        .D(din),
        .Q(sram_dout_40)
    );

    gf180mcu_fd_ip_sram__sram512x8m8wm1 sram_41 (
        .CLK(clk),
        .CEN(sram_ce_n[41]),
        .GWEN(we_n),
        .WEN(8'b0),  // All bits written when GWEN active
        .A(sram_addr),
        .D(din),
        .Q(sram_dout_41)
    );

    gf180mcu_fd_ip_sram__sram512x8m8wm1 sram_42 (
        .CLK(clk),
        .CEN(sram_ce_n[42]),
        .GWEN(we_n),
        .WEN(8'b0),  // All bits written when GWEN active
        .A(sram_addr),
        .D(din),
        .Q(sram_dout_42)
    );

    gf180mcu_fd_ip_sram__sram512x8m8wm1 sram_43 (
        .CLK(clk),
        .CEN(sram_ce_n[43]),
        .GWEN(we_n),
        .WEN(8'b0),  // All bits written when GWEN active
        .A(sram_addr),
        .D(din),
        .Q(sram_dout_43)
    );

    gf180mcu_fd_ip_sram__sram512x8m8wm1 sram_44 (
        .CLK(clk),
        .CEN(sram_ce_n[44]),
        .GWEN(we_n),
        .WEN(8'b0),  // All bits written when GWEN active
        .A(sram_addr),
        .D(din),
        .Q(sram_dout_44)
    );

    gf180mcu_fd_ip_sram__sram512x8m8wm1 sram_45 (
        .CLK(clk),
        .CEN(sram_ce_n[45]),
        .GWEN(we_n),
        .WEN(8'b0),  // All bits written when GWEN active
        .A(sram_addr),
        .D(din),
        .Q(sram_dout_45)
    );

    gf180mcu_fd_ip_sram__sram512x8m8wm1 sram_46 (
        .CLK(clk),
        .CEN(sram_ce_n[46]),
        .GWEN(we_n),
        .WEN(8'b0),  // All bits written when GWEN active
        .A(sram_addr),
        .D(din),
        .Q(sram_dout_46)
    );

    gf180mcu_fd_ip_sram__sram512x8m8wm1 sram_47 (
        .CLK(clk),
        .CEN(sram_ce_n[47]),
        .GWEN(we_n),
        .WEN(8'b0),  // All bits written when GWEN active
        .A(sram_addr),
        .D(din),
        .Q(sram_dout_47)
    );

    // Output multiplexer
    reg [7:0] dout_mux;

    always @(*) begin
        case (sram_sel)
            6'd0: dout_mux = sram_dout_0;
            6'd1: dout_mux = sram_dout_1;
            6'd2: dout_mux = sram_dout_2;
            6'd3: dout_mux = sram_dout_3;
            6'd4: dout_mux = sram_dout_4;
            6'd5: dout_mux = sram_dout_5;
            6'd6: dout_mux = sram_dout_6;
            6'd7: dout_mux = sram_dout_7;
            6'd8: dout_mux = sram_dout_8;
            6'd9: dout_mux = sram_dout_9;
            6'd10: dout_mux = sram_dout_10;
            6'd11: dout_mux = sram_dout_11;
            6'd12: dout_mux = sram_dout_12;
            6'd13: dout_mux = sram_dout_13;
            6'd14: dout_mux = sram_dout_14;
            6'd15: dout_mux = sram_dout_15;
            6'd16: dout_mux = sram_dout_16;
            6'd17: dout_mux = sram_dout_17;
            6'd18: dout_mux = sram_dout_18;
            6'd19: dout_mux = sram_dout_19;
            6'd20: dout_mux = sram_dout_20;
            6'd21: dout_mux = sram_dout_21;
            6'd22: dout_mux = sram_dout_22;
            6'd23: dout_mux = sram_dout_23;
            6'd24: dout_mux = sram_dout_24;
            6'd25: dout_mux = sram_dout_25;
            6'd26: dout_mux = sram_dout_26;
            6'd27: dout_mux = sram_dout_27;
            6'd28: dout_mux = sram_dout_28;
            6'd29: dout_mux = sram_dout_29;
            6'd30: dout_mux = sram_dout_30;
            6'd31: dout_mux = sram_dout_31;
            6'd32: dout_mux = sram_dout_32;
            6'd33: dout_mux = sram_dout_33;
            6'd34: dout_mux = sram_dout_34;
            6'd35: dout_mux = sram_dout_35;
            6'd36: dout_mux = sram_dout_36;
            6'd37: dout_mux = sram_dout_37;
            6'd38: dout_mux = sram_dout_38;
            6'd39: dout_mux = sram_dout_39;
            6'd40: dout_mux = sram_dout_40;
            6'd41: dout_mux = sram_dout_41;
            6'd42: dout_mux = sram_dout_42;
            6'd43: dout_mux = sram_dout_43;
            6'd44: dout_mux = sram_dout_44;
            6'd45: dout_mux = sram_dout_45;
            6'd46: dout_mux = sram_dout_46;
            6'd47: dout_mux = sram_dout_47;
            default: dout_mux = 8'h0;
        endcase
    end

    assign dout = dout_mux;

endmodule