// Chip Top Module with IO Pads
// Generated by sram-forge
// Chip: gf180mcu_ic_1x1_sram_u8b24k
// 24KB SRAM (8-bit x 24K) for 1x1 wafer.space slot
// This is the top-level module with IO pad connections
// Uses GF180MCU IO pad library

module gf180mcu_ic_1x1_sram_u8b24k_top (
    // Power pads (directly connected)
    inout  wire VDD,
    inout  wire VSS,

    // Clock and reset pads
    inout  wire clk_pad,
    inout  wire rst_n_pad,

    // Control pads
    inout  wire ce_n_pad,
    inout  wire we_n_pad,

    // Address pads
    inout  wire addr_pad_0,
    inout  wire addr_pad_1,
    inout  wire addr_pad_2,
    inout  wire addr_pad_3,
    inout  wire addr_pad_4,
    inout  wire addr_pad_5,
    inout  wire addr_pad_6,
    inout  wire addr_pad_7,
    inout  wire addr_pad_8,
    inout  wire addr_pad_9,
    inout  wire addr_pad_10,
    inout  wire addr_pad_11,
    inout  wire addr_pad_12,
    inout  wire addr_pad_13,
    inout  wire addr_pad_14,

    // Data pads (directly inout for simplicity)
    inout  wire data_pad_0,
    inout  wire data_pad_1,
    inout  wire data_pad_2,
    inout  wire data_pad_3,
    inout  wire data_pad_4,
    inout  wire data_pad_5,
    inout  wire data_pad_6,
    inout  wire data_pad_7
);

    // Internal signals
    wire clk_core;
    wire rst_n_core;
    wire ce_n_core;
    wire we_n_core;
    wire [14:0] addr_core;
    wire [7:0] din_core;
    wire [7:0] dout_core;

    // IO Pad instantiations
    // Clock input pad
    gf180mcu_fd_io__in_s clk_pad_inst (
        .PAD(clk_pad),
        .PU(1'b0),
        .PD(1'b0),
        .Y(clk_core)
    );

    // Reset input pad
    gf180mcu_fd_io__in_s rst_n_pad_inst (
        .PAD(rst_n_pad),
        .PU(1'b1),
        .PD(1'b0),
        .Y(rst_n_core)
    );

    // Chip enable input pad
    gf180mcu_fd_io__in_s ce_n_pad_inst (
        .PAD(ce_n_pad),
        .PU(1'b1),
        .PD(1'b0),
        .Y(ce_n_core)
    );

    // Write enable input pad
    gf180mcu_fd_io__in_s we_n_pad_inst (
        .PAD(we_n_pad),
        .PU(1'b1),
        .PD(1'b0),
        .Y(we_n_core)
    );

    // Address input pads
    gf180mcu_fd_io__in_s addr_pad_0_inst (
        .PAD(addr_pad_0),
        .PU(1'b0),
        .PD(1'b1),
        .Y(addr_core[0])
    );
    gf180mcu_fd_io__in_s addr_pad_1_inst (
        .PAD(addr_pad_1),
        .PU(1'b0),
        .PD(1'b1),
        .Y(addr_core[1])
    );
    gf180mcu_fd_io__in_s addr_pad_2_inst (
        .PAD(addr_pad_2),
        .PU(1'b0),
        .PD(1'b1),
        .Y(addr_core[2])
    );
    gf180mcu_fd_io__in_s addr_pad_3_inst (
        .PAD(addr_pad_3),
        .PU(1'b0),
        .PD(1'b1),
        .Y(addr_core[3])
    );
    gf180mcu_fd_io__in_s addr_pad_4_inst (
        .PAD(addr_pad_4),
        .PU(1'b0),
        .PD(1'b1),
        .Y(addr_core[4])
    );
    gf180mcu_fd_io__in_s addr_pad_5_inst (
        .PAD(addr_pad_5),
        .PU(1'b0),
        .PD(1'b1),
        .Y(addr_core[5])
    );
    gf180mcu_fd_io__in_s addr_pad_6_inst (
        .PAD(addr_pad_6),
        .PU(1'b0),
        .PD(1'b1),
        .Y(addr_core[6])
    );
    gf180mcu_fd_io__in_s addr_pad_7_inst (
        .PAD(addr_pad_7),
        .PU(1'b0),
        .PD(1'b1),
        .Y(addr_core[7])
    );
    gf180mcu_fd_io__in_s addr_pad_8_inst (
        .PAD(addr_pad_8),
        .PU(1'b0),
        .PD(1'b1),
        .Y(addr_core[8])
    );
    gf180mcu_fd_io__in_s addr_pad_9_inst (
        .PAD(addr_pad_9),
        .PU(1'b0),
        .PD(1'b1),
        .Y(addr_core[9])
    );
    gf180mcu_fd_io__in_s addr_pad_10_inst (
        .PAD(addr_pad_10),
        .PU(1'b0),
        .PD(1'b1),
        .Y(addr_core[10])
    );
    gf180mcu_fd_io__in_s addr_pad_11_inst (
        .PAD(addr_pad_11),
        .PU(1'b0),
        .PD(1'b1),
        .Y(addr_core[11])
    );
    gf180mcu_fd_io__in_s addr_pad_12_inst (
        .PAD(addr_pad_12),
        .PU(1'b0),
        .PD(1'b1),
        .Y(addr_core[12])
    );
    gf180mcu_fd_io__in_s addr_pad_13_inst (
        .PAD(addr_pad_13),
        .PU(1'b0),
        .PD(1'b1),
        .Y(addr_core[13])
    );
    gf180mcu_fd_io__in_s addr_pad_14_inst (
        .PAD(addr_pad_14),
        .PU(1'b0),
        .PD(1'b1),
        .Y(addr_core[14])
    );

    // Data bidirectional pads
    gf180mcu_fd_io__bi_t data_pad_0_inst (
        .PAD(data_pad_0),
        .A(dout_core[0]),
        .EN(!we_n_core && !ce_n_core),  // Output enable on read
        .PU(1'b0),
        .PD(1'b0),
        .CS(1'b0),
        .SL(1'b0),
        .IE(1'b1),
        .OE(!we_n_core && !ce_n_core),
        .Y(din_core[0])
    );
    gf180mcu_fd_io__bi_t data_pad_1_inst (
        .PAD(data_pad_1),
        .A(dout_core[1]),
        .EN(!we_n_core && !ce_n_core),  // Output enable on read
        .PU(1'b0),
        .PD(1'b0),
        .CS(1'b0),
        .SL(1'b0),
        .IE(1'b1),
        .OE(!we_n_core && !ce_n_core),
        .Y(din_core[1])
    );
    gf180mcu_fd_io__bi_t data_pad_2_inst (
        .PAD(data_pad_2),
        .A(dout_core[2]),
        .EN(!we_n_core && !ce_n_core),  // Output enable on read
        .PU(1'b0),
        .PD(1'b0),
        .CS(1'b0),
        .SL(1'b0),
        .IE(1'b1),
        .OE(!we_n_core && !ce_n_core),
        .Y(din_core[2])
    );
    gf180mcu_fd_io__bi_t data_pad_3_inst (
        .PAD(data_pad_3),
        .A(dout_core[3]),
        .EN(!we_n_core && !ce_n_core),  // Output enable on read
        .PU(1'b0),
        .PD(1'b0),
        .CS(1'b0),
        .SL(1'b0),
        .IE(1'b1),
        .OE(!we_n_core && !ce_n_core),
        .Y(din_core[3])
    );
    gf180mcu_fd_io__bi_t data_pad_4_inst (
        .PAD(data_pad_4),
        .A(dout_core[4]),
        .EN(!we_n_core && !ce_n_core),  // Output enable on read
        .PU(1'b0),
        .PD(1'b0),
        .CS(1'b0),
        .SL(1'b0),
        .IE(1'b1),
        .OE(!we_n_core && !ce_n_core),
        .Y(din_core[4])
    );
    gf180mcu_fd_io__bi_t data_pad_5_inst (
        .PAD(data_pad_5),
        .A(dout_core[5]),
        .EN(!we_n_core && !ce_n_core),  // Output enable on read
        .PU(1'b0),
        .PD(1'b0),
        .CS(1'b0),
        .SL(1'b0),
        .IE(1'b1),
        .OE(!we_n_core && !ce_n_core),
        .Y(din_core[5])
    );
    gf180mcu_fd_io__bi_t data_pad_6_inst (
        .PAD(data_pad_6),
        .A(dout_core[6]),
        .EN(!we_n_core && !ce_n_core),  // Output enable on read
        .PU(1'b0),
        .PD(1'b0),
        .CS(1'b0),
        .SL(1'b0),
        .IE(1'b1),
        .OE(!we_n_core && !ce_n_core),
        .Y(din_core[6])
    );
    gf180mcu_fd_io__bi_t data_pad_7_inst (
        .PAD(data_pad_7),
        .A(dout_core[7]),
        .EN(!we_n_core && !ce_n_core),  // Output enable on read
        .PU(1'b0),
        .PD(1'b0),
        .CS(1'b0),
        .SL(1'b0),
        .IE(1'b1),
        .OE(!we_n_core && !ce_n_core),
        .Y(din_core[7])
    );


    // Core instantiation
    gf180mcu_ic_1x1_sram_u8b24k_core u_core (
        .clk(clk_core),
        .rst_n(rst_n_core),
        .ce_n(ce_n_core),
        .we_n(we_n_core),
        .addr(addr_core),
        .din(din_core),
        .dout(dout_core)
    );

endmodule