// Pad counts for different slot sizes and configurations.
//
// Two configuration types are supported:
// - DEF (default): Mixed pad types (bidir, input, analog) from original configs
// - MAX/SPC/NUM: All bidir pads for maximum signal count (define MAX_IO_CONFIG)
//
// Physical limits per slot (IO cell = 75um, corner = 355um, seal ring = 26um):
// - 1x1:     N/S=42 pads, E/W=58 pads, total=200
// - 0.5x1:   N/S=15 pads, E/W=58 pads, total=146
// - 1x0.5:   N/S=42 pads, E/W=23 pads, total=130
// - 0.5x0.5: N/S=15 pads, E/W=23 pads, total=76

`ifdef SLOT_1X1

`ifdef NUM_DVDD_PADS_OVERRIDE
  `define NUM_DVDD_PADS `NUM_DVDD_PADS_OVERRIDE
`else
  `define NUM_DVDD_PADS 8
`endif
`ifdef NUM_DVSS_PADS_OVERRIDE
  `define NUM_DVSS_PADS `NUM_DVSS_PADS_OVERRIDE
`else
  `define NUM_DVSS_PADS 10
`endif

`ifdef MAX_IO_CONFIG
  // Maximum bidir configuration - no input/analog pads
  `define NUM_INPUT_PADS 0
  `ifdef NUM_BIDIR_PADS_OVERRIDE
    `define NUM_BIDIR_PADS `NUM_BIDIR_PADS_OVERRIDE
  `else
    `define NUM_BIDIR_PADS 168
  `endif
  `define NUM_ANALOG_PADS 0
`else
  // Default configuration - mixed pad types from original slot_1x1.yaml
  `define NUM_INPUT_PADS 12
  `define NUM_BIDIR_PADS 40
  `define NUM_ANALOG_PADS 2
`endif

`endif

`ifdef SLOT_0P5X1

`ifdef NUM_DVDD_PADS_OVERRIDE
  `define NUM_DVDD_PADS `NUM_DVDD_PADS_OVERRIDE
`else
  `define NUM_DVDD_PADS 8
`endif
`ifdef NUM_DVSS_PADS_OVERRIDE
  `define NUM_DVSS_PADS `NUM_DVSS_PADS_OVERRIDE
`else
  `define NUM_DVSS_PADS 8
`endif

`ifdef MAX_IO_CONFIG
  // Maximum bidir configuration - no input/analog pads
  `define NUM_INPUT_PADS 0
  `ifdef NUM_BIDIR_PADS_OVERRIDE
    `define NUM_BIDIR_PADS `NUM_BIDIR_PADS_OVERRIDE
  `else
    `define NUM_BIDIR_PADS 122
  `endif
  `define NUM_ANALOG_PADS 0
`else
  // Default configuration - mixed pad types from original slot_0p5x1.yaml
  `define NUM_INPUT_PADS 4
  `define NUM_BIDIR_PADS 44
  `define NUM_ANALOG_PADS 6
`endif

`endif

`ifdef SLOT_1X0P5

`ifdef NUM_DVDD_PADS_OVERRIDE
  `define NUM_DVDD_PADS `NUM_DVDD_PADS_OVERRIDE
`else
  `define NUM_DVDD_PADS 8
`endif
`ifdef NUM_DVSS_PADS_OVERRIDE
  `define NUM_DVSS_PADS `NUM_DVSS_PADS_OVERRIDE
`else
  `define NUM_DVSS_PADS 8
`endif

`ifdef MAX_IO_CONFIG
  // Maximum bidir configuration - no input/analog pads
  `define NUM_INPUT_PADS 0
  `ifdef NUM_BIDIR_PADS_OVERRIDE
    `define NUM_BIDIR_PADS `NUM_BIDIR_PADS_OVERRIDE
  `else
    `define NUM_BIDIR_PADS 108
  `endif
  `define NUM_ANALOG_PADS 0
`else
  // Default configuration - mixed pad types from original slot_1x0p5.yaml
  `define NUM_INPUT_PADS 4
  `define NUM_BIDIR_PADS 46
  `define NUM_ANALOG_PADS 4
`endif

`endif

`ifdef SLOT_0P5X1_3SIDE

// Half-sized slot_1x1 (west half). 3 sides populated; east edge is the bare cut.
// Pad counts match the WEST half of slot_1x1's padring.

`ifdef NUM_DVDD_PADS_OVERRIDE
  `define NUM_DVDD_PADS `NUM_DVDD_PADS_OVERRIDE
`else
  `define NUM_DVDD_PADS 4
`endif
`ifdef NUM_DVSS_PADS_OVERRIDE
  `define NUM_DVSS_PADS `NUM_DVSS_PADS_OVERRIDE
`else
  `define NUM_DVSS_PADS 6
`endif

`define NUM_INPUT_PADS 12
`define NUM_BIDIR_PADS 14
`define NUM_ANALOG_PADS 2

`endif

`ifdef SLOT_1X0P5_3SIDE

// Half-sized slot_1x1 (north half). 3 sides populated; south edge is the bare cut.
// Pad counts match the NORTH half of slot_1x1's padring (with clk_pad/rst_n_pad
// relocated to PAD_WEST since PAD_SOUTH is empty).

`ifdef NUM_DVDD_PADS_OVERRIDE
  `define NUM_DVDD_PADS `NUM_DVDD_PADS_OVERRIDE
`else
  `define NUM_DVDD_PADS 4
`endif
`ifdef NUM_DVSS_PADS_OVERRIDE
  `define NUM_DVSS_PADS `NUM_DVSS_PADS_OVERRIDE
`else
  `define NUM_DVSS_PADS 5
`endif

`define NUM_INPUT_PADS 6
`define NUM_BIDIR_PADS 20
`define NUM_ANALOG_PADS 2

`endif

`ifdef SLOT_0P5X0P5

`ifdef NUM_DVDD_PADS_OVERRIDE
  `define NUM_DVDD_PADS `NUM_DVDD_PADS_OVERRIDE
`else
  `define NUM_DVDD_PADS 4
`endif
`ifdef NUM_DVSS_PADS_OVERRIDE
  `define NUM_DVSS_PADS `NUM_DVSS_PADS_OVERRIDE
`else
  `define NUM_DVSS_PADS 4
`endif

`ifdef MAX_IO_CONFIG
  // Maximum bidir configuration - no input/analog pads
  `define NUM_INPUT_PADS 0
  `ifdef NUM_BIDIR_PADS_OVERRIDE
    `define NUM_BIDIR_PADS `NUM_BIDIR_PADS_OVERRIDE
  `else
    `define NUM_BIDIR_PADS 62
  `endif
  `define NUM_ANALOG_PADS 0
`else
  // Default configuration - mixed pad types from original slot_0p5x0p5.yaml
  `define NUM_INPUT_PADS 4
  `define NUM_BIDIR_PADS 38
  `define NUM_ANALOG_PADS 4
`endif

`endif

// Exact-pad 3-side configs. Pad counts == the slot_1x1 pads that survive
// on the kept side of a half-size die. Every signal/power pad is pinned
// (via a custom PAD_CFG) to its EXACT slot_1x1 (x,y). The 2 analog pads
// are relocated (not coordinate-preserved) only so NUM_ANALOG_PADS >= 1.
// Counts auto-generated by scripts/generate_exact_3side_configs.py.

`ifdef SLOT_0P5X1_3SIDE_EXACT

// Exact-pad half slot_1x1 (EAST edge = bare cut, keep WEST half).

`ifdef NUM_DVDD_PADS_OVERRIDE
  `define NUM_DVDD_PADS `NUM_DVDD_PADS_OVERRIDE
`else
  `define NUM_DVDD_PADS 4
`endif
`ifdef NUM_DVSS_PADS_OVERRIDE
  `define NUM_DVSS_PADS `NUM_DVSS_PADS_OVERRIDE
`else
  `define NUM_DVSS_PADS 4
`endif

`define NUM_INPUT_PADS 12
`define NUM_BIDIR_PADS 10
`define NUM_ANALOG_PADS 2

`endif

`ifdef SLOT_1X0P5_3SIDE_EXACT

// Exact-pad half slot_1x1 (NORTH edge = bare cut, keep SOUTH half).
// (The approximate slot_1x0p5_3side cuts SOUTH; exact preservation
// requires cutting NORTH since slot_1x1's north pads sit at y~5096
// which cannot exist in a 2561um-tall die.)

`ifdef NUM_DVDD_PADS_OVERRIDE
  `define NUM_DVDD_PADS `NUM_DVDD_PADS_OVERRIDE
`else
  `define NUM_DVDD_PADS 2
`endif
`ifdef NUM_DVSS_PADS_OVERRIDE
  `define NUM_DVSS_PADS `NUM_DVSS_PADS_OVERRIDE
`else
  `define NUM_DVSS_PADS 3
`endif

`define NUM_INPUT_PADS 6
`define NUM_BIDIR_PADS 20
`define NUM_ANALOG_PADS 2

`endif

`ifdef SLOT_0P5X0P5_2SIDE_EXACT

// Exact-pad QUARTER slot_1x1 (NORTH + EAST edges = bare cuts, keep the
// SOUTH-WEST corner).  This is the half-width (cut E) and half-height
// (cut N) exact cases superimposed: only the SOUTH pads with
// x=488.5+i*180 <= 1966-381 (i=0..5) and the WEST pads with
// y=519+i*211 <= 2561-381 (i=0..7) survive, each pinned to its EXACT
// slot_1x1 (x,y).  2 analog pads are relocated (not coordinate-
// preserved) only so NUM_ANALOG_PADS >= 1.

`ifdef NUM_DVDD_PADS_OVERRIDE
  `define NUM_DVDD_PADS `NUM_DVDD_PADS_OVERRIDE
`else
  `define NUM_DVDD_PADS 1
`endif
`ifdef NUM_DVSS_PADS_OVERRIDE
  `define NUM_DVSS_PADS `NUM_DVSS_PADS_OVERRIDE
`else
  `define NUM_DVSS_PADS 1
`endif

`define NUM_INPUT_PADS 6
`define NUM_BIDIR_PADS 4
`define NUM_ANALOG_PADS 2

`endif
